config/routes.rb
Rails.application.routes.draw do
  devise_for :customers

  root 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  resources :surfboards

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :surfboards, through: :my_board
end

app/models/my_board.rb
class MyBoard < ActiveRecord::Base
  belongs_to :customer
  belongs_to :surfboard
end

app/models/surfboard.rb
class Surfboard < ActiveRecord::Base
  has_many :customers, through: :my_board
  before_create :surfboard_email

  def surfboard_email
    SurfboardMailer.new_surfboard_email(self).deliver
  end

  def self.select_board_type(board_type)
    if board_type == "Longboard"
      Surfboard::LONGBOARD_OPTIONS 
    elsif board_type == "Shortboard"
      Surfboard::SHORTBOARD_OPTIONS
    elsif board_type == "Funboard"
      Surfboard::FUNBOARD_OPTIONS
    elsif board_type == "Fish"
      Surfboard::FISH
    end
  end

  BOARD_TYPE = [
    "Longboard",
    "Shortboard",
    "Funboard",
    "Fish"
  ]

  MATERIAL =[
    "Polyurethane",
    "Epoxy"
  ]

  FIN_SETUP =[
    "Thruster",
    "Single",
    "2 + 1",
    "Twin",
    "Quad",
    "Convertible"
  ]

  FIN_TYPE =[
    "FCS",
    "Futures",
    "Glass-on",
  ]

  TAIL = [
    "Squash",
    "Swallow",
    "Rounded",
    "Pin-Tail",
    "Diamond",
    "Rounded-Pin",
    "Fish"
  ]

  GLASSING = [
    "4oz",
    "6oz",
    "Volan",
    "S-Glass"
  ]

  LENGTH = [
    5.10,
    5.11,
    6.0,
    6.1,
    6.2,
    6.3,
    6.4,
    6.5,
    6.6,
    7.0,
    7.2,
    7.4,
    7.6,
    8.0,
    8.6,
    9.0,
    9.6,
    10.0,
  ]

  WIDTH = [
    19.5,
    19.75,
    20.0,
    20.25,
    20.5,
    20.75,
    21.0,
    21.25,
    21.5,
    21.75,
    22.0,
    22.25,
    22.5,
    22.75,
    23.0, 
    23.5,
    24.0
  ]

  THICKNESS = [
    2.0,
    2.25,
    2.5,
    2.75,
    3.0,
    3.25
  ]

  LONGBOARD_OPTIONS = {
    material: MATERIAL,
    fin_setup:["2+1", "Single"],
    fin_type: FIN_TYPE,
    tail:["Squash", "Rounded","Rounded-Pin"],
    glassing: ["Volan", "S-Glass"],
    length: [8.0, 8.6, 9.0, 9.6, 10.0,],
    width: [22.0, 22.25, 22.5, 22.75, 23.0, 23.5, 24.0],
    thickness: [2.5, 2.75, 3.0, 3.25]
  }

  SHORTBOARD_OPTIONS = {
    material: MATERIAL,
    fin_setup:["Thruster", "Convertible"],
    fin_type: FIN_TYPE,
    tail:["Squash", "Swallow", "Rounded", "Diamond"],
    glassing: ["4oz", "6oz"],
    length: [5.10, 5.11, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6],
    width: [19.5, 19.75, 20.0, 20.25, 20.5, 20.75, 21.0, 21.25, 21.5, 21.75, 22.0, 22.25],
    thickness: [2.0, 2.25, 2.5, 2.75] 
  }

  FUNBOARD_OPTIONS = {
    material: MATERIAL,
    fin_setup:["Thruster", "2+1", "single", "Convertible"],
    fin_type: FIN_TYPE,
    tail:["Squash", "Swallow", "Rounded", "Rounded-Pin"],
    glassing: ["4oz", "6oz"],
    length: [6.6, 7.0, 7.2, 7.4, 7.6, 8.0,],
    width: [19.5, 19.75, 20.0, 20.25, 20.5, 20.75, 21.0, 21.25, 21.5, 21.75, 22.0, 22.25],
    thickness: [2.0, 2.25, 2.5, 2.75]
  }

    FISH = {
    material: MATERIAL,
    fin_setup:["Twin", "Quad", "Convertible"],
    fin_type: FIN_TYPE,
    tail:["Squash", "Swallow", "Fish"],
    glassing: ["4oz", "6oz"],
    length: [5.10, 5.11, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 7.0, 7.2],
    width: [20.0, 20.25, 20.5, 20.75, 21.0, 21.25, 21.5, 21.75, 22.0, 22.25],
    thickness: [2.0, 2.25, 2.5, 2.75] 
  }



  # On front end, when you change the type of board,
  # Do an ajax request to the server to find out what the new options are for that board
  # On return from the server, re-populate your select boxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def about
    
  end

  def contact
    
  end
end

app/controllers/surfboards_controller.rb
class SurfboardsController < ApplicationController
  before_filter :find_surfboard, only: [:show, :edit, :update, :destroy]
  def index
    
  end

  # Ajax event fires to new route
  #   it sends across the board_type in the params
  # In the model
  #   We are creating a new method that accepts a board_type param
  #   We are rebuilding the options based on the parameter that is passed in
  #  
  # In new in the controller
  #   We are going to call a method on our Surfboard class and send in the board_type .to_json


  def new
    @surfboard = Surfboard.new
    if params[:board_type].blank?
      params[:board_type] = "Longboard"
    end
    @options = Surfboard.select_board_type(params[:board_type])
    @surfboard.board_type = params[:board_type]
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @surfboard = Surfboard.create surfboard_params
    respond_to do |format|
      format.js
      format.html { redirect_to root_path}
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    @surfboard.update_attributes surfbard_params
    redirect_to root_path 
  end

  def destroy
    @surfboard.delete surfboard_params
    redirect_to root_path
  end
private
  def find_surfboard
    @surfboard = Surfboard.find params[:id]
  end

  def surfboard_params
    params.require(:surfboard).permit(:customer_name,
      :customer_email,
      :customer_phone,
      :board_type,
      :materials,
      :graphics,
      :fin_setup,
      :fin_type,
      :tail,
      :glassing,
      :length,  
      :width,    
      :thickness,
      :special_instructions)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/surfboards_helper.rb
module SurfboardsHelper
end

app/views/home/about.html.haml
=image_tag "richcrop.jpeg"
%br
%br
%p
  Sacrifice breaking ball plunked full count skipper, shutout inning triple play on deck. Third baseman team grounder count off-speed run force. Plunked double play starting pitcher interleague outside check swing base on balls flyout. Fan losses no decision pennant knuckle baltimore chop cup of coffee tigers. Season good eye series left fielder off-speed pinch runner helmet nubber sidearm. Baseball card pennant helmet defensive indifference baseball league hot dog knuckleball game.
%p
  Dodgers pine tar first baseman perfect game contact outfielder away fall classic. Bag error designated hitter small ball in the hole left fielder reliever world series pickoff. Shift sabremetrics dead ball era sacrifice bunt alley, skipper extra innings pitchout. Line drive national pastime pinch runner baseball card cup of coffee around the horn baseline breaking ball baseline. Season out outfielder center fielder cookie corner home designated hitter on deck. Bunt fall classic warning track petey bat rookie diamond home.

app/views/home/contact.html.haml
%h2 We are located at
%p 
  374 Gannett Rd. N.Scituate, MA 02066
  1-781-543-WAVE (9283)

%iframe{:frameborder => "0", :height => "450", :src => "https://www.google.com/maps/embed/v1/place?q=374%20Gannett%20Rd%2C%20Scituate%2C%20MA%2002066%2C%20United%20States%2C%20North%20America&key=AIzaSyDtGIu8XAdRmreYCkYAtiZ2Uo_DRRqqybw", :style => "border:0", :width => "600"}

app/views/home/index.html.haml
%h4
  =link_to "New Board", new_surfboard_path

=image_tag "header_image.jpg"

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %link{:href => "../../assets/ico/favicon.ico", :rel => "shortcut icon"}
    %title Custom Surfboards
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{:role => "document"}
    / Fixed navbar
    .navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Build your board
        .navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li
              = link_to "Home", root_path
            %li
              = link_to "About", about_path
            %li
              = link_to "Contact", contact_path
        / /.nav-collapse
    .container.theme-showcase{:role => "main"}
      .container
        -if notice || alert
          %p.notice= notice
          %p.alert= alert
        = yield

app/views/surfboards/_form.html.haml
%div.order_form
  =form_for @surfboard do |f|
    %div.customer_name{class: "form-group"}
      = f.label :customer_name
      = f.text_field :customer_name, placeholder: "Name" 
    %div.customer_email{class: "form-group"}
      = f.label :customer_email
      = f.text_field :customer_email, placeholder: "Email"
    %div.customer_phone{class: "form-group"}
      = f.label :customer_phone
      = f.text_field :customer_phone, placeholder: "Phone Number"
    %div.board_type{class: "board_type"}
      = f.label :board_type
      = f.select :board_type, options_for_select(Surfboard::BOARD_TYPE, @surfboard.board_type), include_blank: "Select", board_url: new_surfboard_path
    = f.label :materials
    = f.select :materials,  options_for_select(Surfboard::MATERIAL, @surfboard.materials), include_blank: "Select"
    %div.fin_setup{class: "form-group"}
      = f.label :fin_setup
      = f.select :fin_setup,  options_for_select(@options[:fin_setup], @surfboard.fin_setup), include_blank: "Select"
    
    = f.label :fin_type
    = f.select :fin_type,  options_for_select(Surfboard::FIN_TYPE, @surfboard.fin_type), include_blank: "Select"
    %div.tail{class: "form-group"}
      = f.label :tail
      = f.select :tail,  options_for_select(@options[:tail], @surfboard.tail), include_blank: "Select"
    %div.glassing{class: "form-group"}
      = f.label :glassing
      = f.select :glassing,  options_for_select(@options[:glassing], @surfboard.glassing), include_blank: "Select"
    %div.length{class: "form-group"}
      = f.label :length
      = f.select :length, options_for_select(@options[:length], @surfboard.length), include_blank: "Select"
    %div.width{class: "form-group"}
      = f.label :width
      = f.select :width, options_for_select(@options[:width], @surfboard.width), include_blank: "Select"
    %div.thickness{class: "form-group"}
      = f.label :thickness
      = f.select :thickness, options_for_select(@options[:thickness], @surfboard.thickness), include_blank: "Select" 
    %div.graphics{"data-placement" => "right", "data-toggle" => "tooltip", :title => "Tell us what you what your board to look like. Airbrushing, Resin Tint, Acid Spash?", :type => "input"} 
      =f.label :graphics
      =f.text_area :graphics 
    %div.instructions{"data-placement" => "right", "data-toggle" => "tooltip", :title => "This is where you would request options like single to double concave or a step-deck.", :type => "input"} 
      =f.label :special_instructions
      =f.text_area :special_instructions  
     
    %br
    =f.submit "Submit" 
    

app/views/surfboards/new.html.haml
%h3 Desgin your board
= render 'form'
%hr
%h4
  = link_to "Home", root_path

app/views/surfboards/new.js.erb
console.log("<%= @options %>")
$(".order_form").html(
  "<%= escape_javascript(render(partial: 'form', locals:{options: @options})) %>"
  )